### ISSUE TITLE
[FR] Robin Nano v3 support?

### ISSUE THREAD

**Issue by KosVas91** [gloomyandy/RepRapFirmware#100]
Since a while ago, MKS on their GitHub has published an alternative bootloader and RRF 3.2 binaries for MKS Robin Nano V3, can we expect that this board will be supported by TeamGloomy Configurator and more recent RRF versions?

**Comment by jaysuk** [comment]
not at the moment.
It appears they've made other changes than just bootloader but the way
they've uploaded the source makes it very difficult to work out what
changes those are.

Thanks,

Jay

**Comment by KosVas91** [comment]
I do not understand a lot in programming, so my next question most likely will be naive and silly.
Comparing the source code that MKS has published with 3.2_4 build from this GitHub shows that MKS code has only 9 modified files (just few lines difference in each) and 1 new file MKS_ROBIN.h. Do these changes need to be figured out?

![diff](https://user-images.githubusercontent.com/31368477/130987916-6c1118a3-8711-4271-9df3-66e344d3e61e.PNG)

**Comment by Lino77** [comment]
if it helps, these are the changes I made to get it to work with me, and the bootloader, of course
[MKS_Nano.zip](https://github.com/gloomyandy/RepRapFirmware/files/7064452/MKS_Nano.zip)

**Comment by gloomyandy** [comment]
@Lino77 I'm curious as to why you had to disable DMA support for SPI3. What was the problem. I'm not aware of any issues with using SPI3/DMA in other situations.

**Comment by KosVas91** [comment]
@gloomyandy I have tested @Lino77 version and it working fine. May be, you could compile the latest version of RRF (v3.3.0_9+) with NANO v3 PINS/BoardConfig and your vision of correct SPI3/DMA configuration? I will be happy to test it.
It would be really great to get support of NANO v3 by this project, because a NANO v1.2 was/is extremely popular board in Chinese printers and NANO v3 is great drop-in replacement for it.

**Comment by jaysuk** [comment]
I'm pretty sure we won't be supporting this board due to the changes that
are required will require a separate build.

**Comment by Lino77** [comment]
@KosVas91  i build it but untetstet [3.3.0_9_mks_nano.zip](https://github.com/gloomyandy/RepRapFirmware/files/7207695/3.3.0_9_mks_nano.zip)
