### ISSUE TITLE
Upload through wifi always fails on nodemcu with **CH9102**

### ISSUE THREAD

**Issue by kai1-AAA** [gloomyandy/RepRapFirmware#104]
Hello!

Upload through wifi always fails on SKR1.3 + nodemcu with **CH9102** serial ic, everything else is working- web interface, serial connection and configuration of esp is ok too, connects to ssid and other stuff.
tried different builds of main firmware with corresponding DWC and DWSS, but no luck do upload then it give an-  err1 error check summ.

Please help!)

**Comment by jaysuk** [comment]
please use the discord channel for general support https://discord.gg/uS97Qs7
best to use the built in flashing if you can set it up
