### ISSUE TITLE
2x termocouple-max6675 on mks sgen l2?

### ISSUE THREAD

**Issue by whoim2** [gloomyandy/RepRapFirmware#107]
Hello!
I would like to connect two thermistors to mks sgen L 2.0 for 400-450C operation.
I examined the options available and found that the lpc / stm32 port supports an additional type in the M308 command "thermocouple-max6675", the board is cheap as is the thermocouple.
Can I connect two such boards to the spi bus, on which the esp8266 module is located, assigning two additional CS pins from the free ones in EXP2?
Thanks in advance.

**Comment by gloomyandy** [comment]
Please use our discord server for support questions: https://teamgloomy.github.io/support.html

To quickly answer your question. No you can not use the spi bus that is used for the WiFi module for any other purpose, the esp8266 is the bus master of this bus and so it can not be shared with other devices.
