### ISSUE TITLE
BTT-MOT-EXP + SKR v2.0 wiki error

### ISSUE THREAD

**Issue by kintarojs** [gloomyandy/RepRapFirmware#109]
There is an error on pin definition from board.txt : https://teamgloomy.github.io/skr_2.0_btt_mot_exp.html

stepper.enablePins = { E.3, D.6, D.1, C.7, D.13, C.4, E.13, E.12 }
stepper.stepPins = { E.2, D.5, A.15, D.15, D.11, A.7, E.7, A.6 }
stepper.directionPins = { E.1, D.4, A.8, D.14, D.10, B.2, A.4, A.5 }
stepper.TmcUartPins = { E.0, D.3, D.0, C.6, D.12, E.11, **B.9**, B.0 }

should be

stepper.enablePins = {E.3, D.6, D.1, C.7, D.13, C.4, E.13, E.12}
stepper.stepPins = {E.2, D.5, A.15, D.15, D.11, A.7, E.7, A.6}
stepper.directionPins = {E.1, D.4, A.8, D.14, D.10, B.2, A.4, A.5}
stepper.TmcUartPins = {E.0, D.3, D.0, C.6, D.12, E.11, **E.9**, B.0}

PB9 is for I2C usage (https://teamgloomy.github.io/skr_2.0_pins.html)

**Comment by jaysuk** [comment]
thanks, fixed
