### ISSUE TITLE
Extrude not working

### ISSUE THREAD

**Issue by sankafola** [gloomyandy/RepRapFirmware#110]
i have SKR PRO , when i do Extrude the printer do retract

**Comment by sankafola** [comment]
to make sure its true i put back ver 6.1 ([gloomyandy/RepRapFirmware] New release published: v3.4.0beta6_1 ) and etrude working fine

**Comment by gloomyandy** [comment]
Please use our discord server for support, it's much easier for us to handle issues over there: https://teamgloomy.github.io/support.html

**Comment by gloomyandy** [comment]
This can be worked around by adding the following line to your board.txt file:
```
heat.spiTempSensorCSPins = {NoPin, NoPin, NoPin, NoPin, NoPin, NoPin, NoPin, NoPin}
```
It will be fixed in the next (post 3.4beata7_2 release).

**Comment by sankafola** [comment]
thank you for your fast reply

**Comment by sankafola** [comment]
thanks for your support
