### ISSUE TITLE
Extruder only retract after upgrade to 3.4.0 Beta 07

### ISSUE THREAD

**Issue by hliebscher** [gloomyandy/RepRapFirmware#111]
since upgrade the extruder only retract after upgrade from beta 6
extrude and retract the motor goes retract !
if i change 

M569 P3 S0 D3 V30 T4 Y1:2     to  S1

is the same direction ...
Driver 2209 
 
Board: biquskrpro_1.1 (STMWiFi)
Firmware: RepRapFirmware for STM32F4 based Boards 3.4.0beta6_1 (2021-11-06)
[config.g.txt](https://github.com/gloomyandy/RepRapFirmware/files/7780598/config.g.txt)

after downgrade it works ....
the config files are the same

**Comment by jaysuk** [comment]
This is a known issue. Add
```
heat.spiTempSensorCSPins = {NoPin, NoPin, NoPin, NoPin, NoPin, NoPin, NoPin, NoPin}
```
to your board.txt.
It will be fixed in the next beta release.
