### ISSUE TITLE
Assembly of a project

### ISSUE THREAD

**Issue by Golfsyn** [gloomyandy/RepRapFirmware#112]
Good afternoon. Set up your computer according to your recommendations, downloaded and installed all third-party programs, using VSCod downloaded and installed RRFBuild v3.4-dev.
![Image 1](https://user-images.githubusercontent.com/61970952/149622156-56d937ac-fffe-4b87-8190-6069b0920296.jpg)

Then I select the build STM WIFI firmware terminal task and get an error
![Image 2](https://user-images.githubusercontent.com/61970952/149622278-ce23f5ac-9be8-43e4-93b7-ca0fa2d52a5f.jpg)

Downloaded firmware 3.4-dev and RRF 3.4beta7 Source code, still a mistake. Tell me what you can do.

**Comment by gloomyandy** [comment]
Unfortunately I can't understand the error messages being displayed, sorry! Are you using the correct version of Make? I would suggest that you use GNU Make 3.81. If you are still having problem you may want to join our discord server, that's what we prefer to use to handle support issues like this.
