### ISSUE TITLE
Anybody compile 3.4 for LPC?

### ISSUE THREAD

**Issue by whoim2** [gloomyandy/RepRapFirmware#113]
Without accel, 5160 support, etc. Maybe, only for each boards (need for MKS sgen 2).
I want use shaper with x/y frequency apart.

**Comment by jaysuk** [comment]
This won't be possible as the LPC boards are already super constrained with 3.3.
Rather than invest time and effort on something thats not possible, you'd be better off upgrading to an STM32 board.
