### ISSUE TITLE
Wifi Interface dont work

### ISSUE THREAD

**Issue by goldjunge91** [gloomyandy/RepRapFirmware#12]
- WiFi -
Network state is changingMode
WiFi module is idle
Failed messages: pending 0, notready 0, noresp 2
Failed to get WiFi status
Socket states: 0 0
WiFi module is connected to access point BEAGLE_2.4G, IP address 192.168.2.60
WiFi module is idle
WiFi reported error: 
WiFi module is in an unknown state
Error retrieving WiFi status message: bad reply format version
[ERROR] Error retrieving WiFi status message: bad reply format version

WiFi module is connected to access point BEAGLE_2.4G, IP address 192.168.2.60
WiFi module is idle
WiFi module is connected to access point BEAGLE_2.4G, IP address 192.168.2.60
WiFi module is idle
WiFi module is connected to access point BEAGLE_2.4G, IP address 192.168.2.60
WiFi module is idle
WiFi module is connected to access point BEAGLE_2.4G, IP address 192.168.2.60
WiFi module is idle
Error retrieving WiFi status message: bad reply format version
[ERROR] Error retrieving WiFi status message: bad reply format version

WiFi module is connected to access point BEAGLE_2.4G, IP address 192.168.2.60
WiFi module is idle
Attempted to write invalid text to console, which could be due to an invalid baudrate
WiFi module is idle
WiFi module is connected to access point BEAGLE_2.4G, IP address 192.168.2.60
WiFi module is idle
WiFi module is connected to access point BEAGLE_2.4G, IP address 192.168.2.60
WiFi module is idle
WiFi reported error: 
WiFi module is in an unknown state
Error retrieving WiFi status message: bad reply format version
[ERROR] Error retrieving WiFi status message: bad reply format version

WiFi module is connected to access point BEAGLE_2.4G, IP address 192.168.2.60
WiFi module is idle

**Comment by gloomyandy** [comment]
Sorry I've only just seen this. If you are still having this problem, please use either the RepRap forum or the Discord server and we will try and help.
