### ISSUE TITLE
LPConfigurator

### ISSUE THREAD

**Issue by Crunch69** [gloomyandy/RepRapFirmware#15]
First I would like to say this is awesome work every version gets better.  I wish I had the ability to assist with this project.
I think the LPConfigurator is not up to date

**Comment by eightheads** [comment]
I noticed tonight the stepper sections labels are in the wrong positions
<img width="1160" alt="Screen Shot 2020-07-10 at 10 04 32 PM" src="https://user-images.githubusercontent.com/13207144/87215172-595af580-c2f9-11ea-8f00-31815f1a9b74.png">

As compared to the Duet configurator
<img width="1157" alt="Screen Shot 2020-07-10 at 10 05 23 PM" src="https://user-images.githubusercontent.com/13207144/87215193-83141c80-c2f9-11ea-8090-7d9104e0461f.png">

**Comment by jaysuk** [comment]
Thanks eightheads for pointing that out.
It has now been fixed
