### ISSUE TITLE
No matter what I do, the duet web control page says "Failed to connect to 192.168.168.101 DCS not started"

### ISSUE THREAD

**Issue by Bluesandbox** [gloomyandy/RepRapFirmware#17]
Ive checked the wires connecting my raspi to my skr 1.3, they are all correct, yet no matter what i do it always says it cant connect. I have the firmware on the skr and on the raspi.

**Comment by jaysuk** [comment]
Please could you access support through either [discord](https://discord.gg/uS97Qs7) (which is the more preferable option) or the [reprap forum](https://reprap.org/forum/read.php?147,874661)
That way, we can help you much more easily rather than back and forth in here.
