### ISSUE TITLE
How to connect correctly Ormerod IR sensor in analog mode?

### ISSUE THREAD

**Issue by evgen2910** [gloomyandy/RepRapFirmware#20]
i connect in digital mode, but want to connect right in analog (same as to Duet board). If i connect the sensor in analog mode, sensor dosn`t work... 
I change M558 P1 (from P1 to P10), but nothing change (sensor not working or pin does not support a connection )

In digital mode work with M574 Z1 S2 & M558 P1 C"e1temp" H5 F200 T9000 I0 R0.5

**Comment by jaysuk** [comment]
According to the wiki, P1 is analogue

> P1 specifies an unmodulated or smart IR probe, or any other probe type that emulates one (probe output is an analog signal that rises with decreasing nozzle height above the bed). If there is a control signal to the probe, it is driven high when the probe type is P1.

P10 is used for stall detection in RRF 2 but is not used in RRF 3 

> Only one Z probe can be type 1,2,3,5 or 9. 

Also, if you're using the probe as a probe and not as an endstopm M574 Z1 S2 is not required.
