### ISSUE TITLE
Max31855

### ISSUE THREAD

**Issue by overdrive2max** [gloomyandy/RepRapFirmware#23]
Hi
Is it possible to use a MAX31855 termocouple amplifier with this port of the RRF?

**Comment by jaysuk** [comment]
yes, it should be possible. We've had users report success before

**Comment by overdrive2max** [comment]
Thank you for your response. 
My wifi disconnects as soon as I call:
M308 S1 P"P3.26" Y"thermocouple-max31855"
CLK connected to 0.15 and SO connected to 0.17
Do I need to specify anything extra?

**Comment by jaysuk** [comment]
```
board.txt
//Soft SPI Temp sensor to use with MAX31865+PT100
softwareSPI.pins = {1.18,1.19,1.20}
heat.spiTempSensorCSPins = {1.21, NoPin}
heat.spiTempSensorChannel = 2


Gcode
M308 S1 P"P1.21" Y"rtd-max31865"
```

The above is based on the MAX31865 from the user that got it working

**Comment by overdrive2max** [comment]
Thank you. I will try that shortly.

**Comment by overdrive2max** [comment]
It is working. Thank you very much for the assistance.
