### ISSUE TITLE
Simulation Times

### ISSUE THREAD

**Issue by xxsteven69xx** [gloomyandy/RepRapFirmware#27]
![perdiced sim time](https://user-images.githubusercontent.com/20728844/90321070-0da8f680-df0c-11ea-94a1-ddf1b886060f.PNG)
![Slicer time](https://user-images.githubusercontent.com/20728844/90321072-10a3e700-df0c-11ea-8d3b-a12b8b5f1875.PNG)

I'm running the SKR 1.4 Turbo in SBC mode with a raspberry pi 3b+. Running the simulation mode takes 2-3 times longer than the duet wifi im using with the same gcode. The results reported in the console are off and the gcode file isn't updated with the simulation time and is not displayed in the web interface.
That's all I've noticed so far and have been printing great! Thanks for this cool project!
Steven Smith

**Comment by jaysuk** [comment]
The LPC is a slower board than the duet WiFi so the simulation times will be slower.
Simulation times not being saved when an SBC is connected is a known issue with RRF and also affects the duet 3.
