### ISSUE TITLE
missing firmware for the screen bigtree TFT 7" for reprap

### ISSUE THREAD

**Issue by sankafola** [gloomyandy/RepRapFirmware#28]
I have SKR 1.4 turbo and bigtree TFT 7" and i cant find the right firmware for the screen for reprap

**Comment by jaysuk** [comment]
That's not part of this project. We only support RRF on the LPC and not any firmware for any screens

**Comment by sankafola** [comment]
hi,
    you have done an amazing job and i followed every step but no screen if you can help with please a firmware RRF for bigtree TFT LCD
