### ISSUE TITLE
[FR] Shutdown SBC after printjob finish

### ISSUE THREAD

**Issue by wolfgangmauer** [gloomyandy/RepRapFirmware#33]
In combination with a Relay it would be nice if it is possible to shutdown the SBC after print is finish, before power off

**Comment by P-C-R** [comment]
@gloomyandy is doing something like this!

**Comment by P-C-R** [comment]
You could add this on the pi
https://www.quartoknows.com/page/raspberry-pi-shutdown-button


Then Connect it to the Same Signal and ground Line as the relay modul or make a new one M950
 and Trigger IT with the M42 comnand

**Comment by P-C-R** [comment]
Or @wolfgangmauer

**Comment by P-C-R** [comment]
https://github.com/wilriker/execonmcode

**Comment by wolfgangmauer** [comment]
panic: dial unix /var/run/duet.sock: connect: no such file or directory :-(

and M7722

Warning: M7722: Command is not supported

**Comment by P-C-R** [comment]
Will test it this weekend!

**Comment by P-C-R** [comment]
Tested it with my SKR GTR and the SBC. Worked!
I only got your first error message when the PI was not connected to the SKR! Will try later with a SKR 1.3

**Comment by P-C-R** [comment]
The M7722 Error will come Always. Because its no rrf command. But the Pi will See it

**Comment by wolfgangmauer** [comment]
I think the installed golang version is too old

**Comment by P-C-R** [comment]
? have you testetd it with the PI and SKR connected? I downloaded the armv7 version from here
https://github.com/wilriker/execonmcode/releases/tag/v5.1

**Comment by wolfgangmauer** [comment]
Upps, sorry,
I will try....

**Comment by P-C-R** [comment]
I will later make an Tutorial!

Best

Wolfgang Mauer <notifications@github.com> schrieb am Sa., 29. Aug. 2020,
14:56:

**Comment by wolfgangmauer** [comment]
Would be very great!
Thanks a lot!!!

**Comment by wolfgangmauer** [comment]
With the "correct" binary and service, M7722 works

**Comment by P-C-R** [comment]
nice to hear!

**Comment by P-C-R** [comment]
for making a service out of it see:
https://www.raspberrypi.org/documentation/linux/usage/systemd.md

**Comment by wolfgangmauer** [comment]
Found the service-page already ;-)
Is there something like a "jobfinish.g" or put it in slicer instead?

**Comment by P-C-R** [comment]
a sample file is in the repo from execonmcode

**Comment by P-C-R** [comment]
You can Put IT in the slicer or in a macro. You can call every macro with
M98 P"macroname.g"

Wolfgang Mauer <notifications@github.com> schrieb am Sa., 29. Aug. 2020,
15:18:

**Comment by wolfgangmauer** [comment]
I think I choose the slicer, the shutdown is triggered mostly at night when print is finished

**Comment by P-C-R** [comment]
Yep but Oh could write in your endcode of the slicer the M98 command.

And then create the macro at dwc with the ATX and SBC shutdown command ;)

Wolfgang Mauer <notifications@github.com> schrieb am Sa., 29. Aug. 2020,
15:25:

**Comment by P-C-R** [comment]
For Future reference

https://youtu.be/WxcLDUF9zMs

And
https://youtu.be/q2Wl0Ew97PU

**Comment by wolfgangmauer** [comment]
Works perfect, close this?

**Comment by gloomyandy** [comment]
Thanks

**Comment by CrazyCreator13** [comment]
hello ... I think the script is running fine on my pi with connected duet 3 ... but M7722 give me the popup 

Warning: M7722: Command is not supported

and the pi is running always
