### ISSUE TITLE
Minor bug in wiki (wrong link)

### ISSUE THREAD

**Issue by HaernCalistinson** [gloomyandy/RepRapFirmware#36]
On the page for connecting a SBC to the GTR board  (https://github.com/gloomyandy/RepRapFirmware/wiki/SKR-GTR-SBC), the link for the board pinout directs to the Pro board pin diagram and not the GTR board pin diagram. The pinouts are almost identical except for PF12 / PB10. On the linked diagram, PB10 is in the stallguard header, on the GTR diagram it's in EXP2

**Comment by P-C-R** [comment]
one for @jaysuk

**Comment by jaysuk** [comment]
fixed
