### ISSUE TITLE
[FR] Please provide PlatformIO(Windows/Linux).

### ISSUE THREAD

**Issue by wolfgangmauer** [gloomyandy/RepRapFirmware#37]
It would be very nice if there was a PlatformIO project witch fits to the RRF_LPC
Or even update BuildInstructions.md

**Comment by wolfgangmauer** [comment]
Just begin with [gloomyandy/CoreLPC4RRF](https://github.com/gloomyandy/CoreLPC4RRF) and everything works

**Comment by gloomyandy** [comment]
Sorry I really do not like PlatformIO, I see no real benefit in using it and my experience of it with Marlin is that it is basically the source of many problems (with versions of components/tools changing without people realising plus numerous odd problems that seem to require deleting and reinstalling various parts of platformio). 

The build system for this project will be changing considerably as I plan to bring the LPC and STM32F4 ports together into a more unified version.

**Comment by wolfgangmauer** [comment]
Sorry, it was my fault ;-)
I missed CoreLPC4RRF, there is .sh to create the Hole project.
Everything is fine.

**Comment by gloomyandy** [comment]
No problem. This is all changing pretty quickly at the moment I hope to make it a little easier in the future but it all takes time!
