### ISSUE TITLE
DWC crash

### ISSUE THREAD

**Issue by Ducati87** [gloomyandy/RepRapFirmware#43]
Hello, I'm having ad issue every time I launch a print, the DWC and Wifi ESP module go in crash, it lost the wifi connection but the print starts equally.
The DWC is at latest version, everithing works outside of this. 
How can I fix it?
Thank you.

**Comment by gloomyandy** [comment]
Please use the discord channel for help and the initial reporting of potential problems. You can find details of how to join the discord server in the Wiki.
