### ISSUE TITLE
esp32 support

### ISSUE THREAD

**Issue by hinteor** [gloomyandy/RepRapFirmware#47]
can you add esp32 support like esp8266 to the project?

**Comment by gloomyandy** [comment]
Why? Just to replace the esp8266 as the WiFi interface? What advantage would doing that bring?

The esp32 uses a different SDK and so switching to it will require pretty much a rewrite of the code, then there would need to be adaptor boards to support the esp32 etc. So overall there would need to be a good reason to do it.

**Comment by hinteor** [comment]
ok, no reason. just buy esp8266. you can close the Issue
