### ISSUE TITLE
Typo in the Sbase Manual

### ISSUE THREAD

**Issue by P-C-R** [gloomyandy/RepRapFirmware#5]
https://github.com/gloomyandy/RepRapFirmware/wiki/MKS-Sbase-Ethernet

it says
 

> You will also need a board.txt file in the sys folder. Below are the contents that should be used. If using this with an SKR v1.3, change the lpc.board value to biquskr_1.3 

but the example says already sbase ;)

**Comment by jaysuk** [comment]
Thanks. I've removed reference to SKR
