### ISSUE TITLE
Wifi not working with SKR 1.4 Turbo

### ISSUE THREAD

**Issue by yongtheskill** [gloomyandy/RepRapFirmware#52]
Hi, I am using the latest firmware release (3.1.1-14) on my SKR 1.4 Turbo with DuetWebControl Version 3.1.1.
I flashed an ESP8266 with the latest release of Duet WiFi Socket Server for LPC1768 version of RRF, and wired it up on a breadboard according to the wiki.

When I connect to the printer through Pronterface and send `M552 S0`, the LED on my esp flashes once and I get
```>>> m552 s0
SENDING:M552 S0
WiFi module started
Error retrieving WiFi status message: bad reply format version
[ERROR] Error retrieving WiFi status message: bad reply format version

Error retrieving WiFi status message: bad reply format version
[ERROR] Error retrieving WiFi status message: bad reply format version
```

When i then try to send `M587 S"SSID" P"password"` (with my actual SSID and password), the LED on the esp stays off and I get
```>>> M587 S"SSID" P"password"
SENDING:M587 S"SSID" P"password"
Error: M587: Failed to add SSID to remembered list
[ERROR] Error: M587: Failed to add SSID to remembered list
```

Then, when I send `M552 S1`, the LED on the esp flashes once and I get
```>>> M552 S1
SENDING:M552 S1
Failed to change WiFi mode (code -10)
```

After turning the printer off and on again, when I send `M552 S0`, the LED on the esp flashes once and I get
```>>> M552 S0
SENDING:M552 S0
WiFi module started
Error: Failed to initialise WiFi module, code -10
[ERROR] Error: Failed to initialise WiFi module, code -10
```

**Comment by gloomyandy** [comment]
Please use the discord server for support, there are many, many people using WiFi with 3.1.1-14 so I'm pretty sure there is a problem with your setup rather than any sort of bug.
