### ISSUE TITLE
how to use Aux-1 Pin

### ISSUE THREAD

**Issue by goldjunge91** [gloomyandy/RepRapFirmware#59]
Hi
i use on Marlin P0.03.A6 its a  pin from AUX-1 connector i use this for my e3d PT1000 board how can i setup this on reprap ?

**Comment by P-C-R** [comment]
Hello, just use the pin in the M308 command like

M308 S1 P"2.0" Y"rtd-max31865"

**Comment by P-C-R** [comment]
@goldjunge91?
