### ISSUE TITLE
Wrong link in the main readme

### ISSUE THREAD

**Issue by P-C-R** [gloomyandy/RepRapFirmware#6]
To support the number of different boards, a /sys/board.txt config file on the SDCard is used to configure the hardware pin assignments. Some example board config files can be found **here**

The example board config files are redirected to the "old" repo

Best

**Comment by jaysuk** [comment]
One for gloomyandy

**Comment by gloomyandy** [comment]
We are probably going to rework the main README.md file. For now I've edited it to add a pointer to more up to date information.

Thanks!

**Comment by jaysuk** [comment]
readme updated
