### ISSUE TITLE
Relevant info missing in wiki: BTT-EXP-MOT v1.0

### ISSUE THREAD

**Issue by andersop91** [gloomyandy/RepRapFirmware#62]
Hi, 
Have experienced that the EXP-MOT-support is first implemented after last stable build. 
From my point of view, this is only mentioned in the ToDo-list and the changelogs, but should also be mentioned in the wiki:

https://github.com/gloomyandy/RepRapFirmware/wiki/PCR-Driver-Adaptor 

Also, it is written "The defining of the pins is not required on the latest unstable builds." 
This is correct, but from my experience, defining them makes things NOT work. This is recommended writing more explicit for new users.

I couldn't find and option to make a pull request to the wiki, so I put it here. If there is an option, i can of course write a request, if i'm given the proper instructions 👍

**Comment by jaysuk** [comment]
wiki updated stating its only supported from beta 1 onwards and they are automatically mapped from beta 2 onwards
