### ISSUE TITLE
Failed to connect to IP, rrf 3.2_1

### ISSUE THREAD

**Issue by McPaul0** [gloomyandy/RepRapFirmware#63]
Upgrade firmware from 3.1.1-14 to 3.2_1 and now I cant open DWC.
It connects, but throws errors: 
**- Connected to 192.168.1.35
- Failed to connect to ...
- Failed to get files list
- Connection interrupted, attempting to reconnect
- Connection established**

But the blue frame "Connecting..." doesn't dissappear.

After 3-8 reload the page it may open DWC normally, or not.

MicroSD card formatted, changed - no effect
The firmware for Wifi 1.25-01
SKR1.4 turbo.

**Comment by jaysuk** [comment]
can you join us on discord for support please https://discord.gg/uS97Qs7
