### ISSUE TITLE
Telnet issues

### ISSUE THREAD

**Issue by The-Moops** [gloomyandy/RepRapFirmware#68]
I can't seem to connect to my LPC board through Telnet, I've enabled it through M586 and it looks like it tries to connect but instantly fails. Is there some config step I'm missing?

**Comment by jaysuk** [comment]
Telnet isn't supported on the LPC builds

https://teamgloomy.github.io/lpc_differences.html

Thanks,

Jay

**Comment by The-Moops** [comment]
Thanks, not sure how I didn't catch that. I'm assuming no plans for future support given the lack of RAM?

**Comment by jaysuk** [comment]
Yep, unfortunately there are no plans to activate Telnet support.
Ram and the lack of concurrent connections are the main issues.

The STM32 builds do not have this restriction

Thanks,

Jay

**Comment by gloomyandy** [comment]
Note that Telnet is not currently supported on the STM32F4 versions either, I've never really seen the need.
