### ISSUE TITLE
Idea: Change compiler directives into generic STM32 one

### ISSUE THREAD

**Issue by ArkadiuszRaj** [gloomyandy/RepRapFirmware#69]
As I am closer and closer to finish soldering of my printer board build on top of STM32H7 chip,  I have started to look into RRF preparation.

To my surpise your code is not tied to STM32F4 at all. All the changes are generic for STM32 family.
Thus I suggest to:

- change STM32F4 into __ STM32 __ and then add STM32F4 / STM32F7 etc if needed.
- add compiler define for clock selection (i.e. allow easy change of TM1/5 to something else)
- add compiler option for Rsense value (which can be different if different board designs)

I have already prepared code that uses __STM32__. Of course RRFBuild scripts shall be corrected accordingly, but thi sis trivial change. So if you agree I can prepare PR with aforementioned changes.

**Comment by gloomyandy** [comment]
Please use the discord server for discussions like this.
