### ISSUE TITLE
v3.2+ .bin releases for Ethernet boards aka Smoothieboard and Sbase

### ISSUE THREAD

**Issue by kr15uk** [gloomyandy/RepRapFirmware#73]
Seems to be last ethernet variant release is 3.1.1-14 would appreciate 3.2+

Thanks

**Comment by jaysuk** [comment]
You won't get it.
Support was dropped which is why 3.1.1-14 is the last ethernet release

Thanks,

Jay

**Comment by kr15uk** [comment]
Fair enough. Thanks.
