### ISSUE TITLE
[FAQ] Control multiple LPC's with one Pi

### ISSUE THREAD

**Issue by wolfgangmauer** [gloomyandy/RepRapFirmware#75]
Is this possible?

**Comment by jaysuk** [comment]
no

Thanks,

Jay

**Comment by billhu1996** [comment]
Is possible run sbc in  docker container or vm? It may be feasible to solve the problem of gpio accessing docker.

**Comment by jaysuk** [comment]
That's something to pick up with the duet team as we just use what they
produce
