### ISSUE TITLE
not compiling for STM32

### ISSUE THREAD

**Issue by dineshvyas** [gloomyandy/RepRapFirmware#79]
VSCode gives Error. possible reason absence of stdbool.h file in repo. screenshot included. 
![error](https://user-images.githubusercontent.com/55104840/113543774-b2478800-9604-11eb-9117-1c6931fa8257.JPG)
![problems](https://user-images.githubusercontent.com/55104840/113543788-b8d5ff80-9604-11eb-9281-f97b934ad93b.JPG)
any direction?

**Comment by gloomyandy** [comment]
No real idea, quite a few people have been able to build from source so it is almost certainly a problem with your configuration. It looks like you are getting errors in the makefiles (Ignore the problems reported by vscode, I've made no effort to clean any of those up), so I'd start by looking there. What version of make do you have installed?

The new Wiki does not include information of building from source, but you may find the old one useful...
https://github.com/gloomyandy/RepRapFirmware/wiki/build-instructions

**Comment by jaysuk** [comment]
There's this page on the new wiki
https://teamgloomy.github.io/firmware_build.html

**Comment by dineshvyas** [comment]
I followed steps as described in page mentioned https://github.com/gloomyandy/RepRapFirmware/wiki/build-instructions.
my make version is 3.81.2525.1772.
![errors](https://user-images.githubusercontent.com/55104840/113656697-06607400-96ba-11eb-8d68-6b594f48326e.JPG)

**Comment by gloomyandy** [comment]
Ignore the vscode "problems" tab, what you need to do is concentrate on getting make to actually build the project. What errors are you getting from the make process. Many others have been able to build the project, so something is wrong with how you have things setup. Have you made any changes to the makefiles (or any other files).

**Comment by dineshvyas** [comment]
I haven't changed anything in anyfile. However i will continue to dig it. Thanks for all the help. Kindly keep this ticket open.

**Comment by WonderRat** [comment]
Your compiler must have stdbool.h. Check environment variables, paths for includes.
If nothing helps you can google that file and copypaste it, but you can get errors about missing other std*.h

**Comment by dineshvyas** [comment]
> Your compiler must have stdbool.h. Check environment variables, paths for includes.
> If nothing helps you can google that file and copypaste it, but you can get errors about missing other std*.h

Yes exactly after copying stdbool.h it give error for more missing .h files. however I installed make version 4.3 and it didn't change anything. platformIO could an option here.

**Comment by jaysuk** [comment]
no issues when compiling here. 
Just taken a snapshot of all the required repositories, dropped them into vscode in the appropriate folders and its compiled fine.
no changes or dependencies required
