### ISSUE TITLE
BTT or STM related typical flashing issues via TF slot

### ISSUE THREAD

**Issue by sq4nyy** [gloomyandy/RepRapFirmware#85]
I am experiencing it the third time - with third mb from BTT - beginning from SKR 1.2, then 2.0 and now the RRF. They supply 128MB cards, but they never worked for me. I used some old 512Mb card which always worked, but not with the RRF. The RRF started flashing after formatting the TF as FAT and smallest possible allocation size (Windows 10, can't remember exact size now). 
It is STM (possibly bootloader related) or it is the BTT's screwed job. 
So: I prepared files according to your links you sent me in another thread and the board doesn't even start flashing after formatting TF as FAT32. Using FAT it flashes the board (second led blinks indicating EEPROM or SD operations, then stops) but after all I still don't get any output on standard E3 LCD.

**Comment by jaysuk** [comment]
Best to join us on discord so we can troubleshoot your issues properly.
https://discord.gg/uS97Qs7
