### ISSUE TITLE
UART not being detected on MKS SGEN L v2.0

### ISSUE THREAD

**Issue by PsyonicOne** [gloomyandy/RepRapFirmware#86]
I have a MKS SGEN L v2.0 with MKS TMC2209 v2.0 drivers. I have UART jumper pins as per the docos from Makerbase here:
[https://github.com/makerbase-mks/MKS-SGEN_L-V2/wiki/Drivers_MKS_TMC2209]()
Their video here:
[https://www.youtube.com/watch?v=eF8Mqa2Y3oo]()
Which they claim is the same as the v1.0 but I find other videos for v1.0 stating different. Like this one:
[https://www.youtube.com/watch?v=GCX3dc_AWm4&t=74s]()

Using the jumper setting from the Makerbase video I cannot get UART mode to work with your firmware.

I've asked on your Discord channel and was told everything looks to be set up correctly.
Perhaps this is a bug, or bad hardware?
Any help would be appreciated.

Output from M122:
Send: N6 M122*36
Recv: === Diagnostics ===
Recv: RepRapFirmware for LPC176x based Boards (mkssgenl_2.0) version 3.2.2_2 running on LPC176x at 120Mhz
Recv: Used output buffers: 1 of 16 (3 max)
Recv: === RTOS ===
Recv: Static ram: 4956
Recv: Dynamic Memory (RTOS Heap 5): 7992 free, 7968 never used
Recv: Allocations: 222 Frees: 65
Recv: Never used RAM 256, free system stack 76 words
Recv: Tasks: NETWORK(ready,497) HEAT(blocked,249) MAIN(running,352) IDLE(ready,21)
Recv: Owned mutexes: USB(MAIN)
Recv: === Platform ===
Recv: Last reset 00:00:26 ago, cause: [power up]
Recv: Last software reset details not available
Recv: Error status: 0x00
Recv: Aux0 errors 0,0,0
Recv: Supply voltage: under voltage events: 0
Recv: Driver 0: position 0, no-driver-detected
Recv: Driver 1: position 0, no-driver-detected
Recv: Driver 2: position 0, no-driver-detected
Recv: Driver 3: position 0, no-driver-detected
Recv: Driver 4: position 0
Recv: Driver 5: position 0
Recv: Driver 6: position 0
Recv: Date/time: 1970-01-01 00:00:00
Recv: Slowest loop: 15.80ms; fastest: 0.11ms
Recv: Step timer: target 0 count 26753337 delta -26753338 late 0
Recv: USBSerial connected 1
Recv: ADC not ready 2 ADC error threshold 10 ADC Init 1
Recv: Ints: 3545; Calls 3545; fast: 2uS; slow 3uS adj 0 bad 0 big delta 0
Recv: PWM Channels
Recv: Delta -772540556 Start -1 End -1
Recv: === Storage ===
Recv: Free file entries: 6
Recv: SD card 0 detected
Recv: SD card longest read time 1.3ms, write time 0.0ms, max retries 0
Recv: === Move ===
Recv: DMs created 40, maxWait 0ms, bed compensation in use: none, comp offset 0.000
Recv: === DDARing ===
Recv: Scheduled moves 0, completed moves 0, hiccups 0, stepErrors 0, LaErrors 0, Underruns [0, 0, 0], CDDA state -1
Recv: === Heat ===
Recv: Bed heaters = 0, chamberHeaters = -1
Recv: === GCodes ===
Recv: Segments left: 0
Recv: Movement lock held by null
Recv: HTTP is idle in state(s) 0
Recv: File is idle in state(s) 0
Recv: USB is ready with "M122" in state(s) 0
Recv: Aux is idle in state(s) 0
Recv: Trigger is idle in state(s) 0
Recv: Queue is idle in state(s) 0
Recv: Daemon is idle in state(s) 0
Recv: Autopause is idle in state(s) 0
Recv: Code queue is empty.
Recv: === Network ===
Recv: Slowest loop: 1.02ms; fastest: 0.00ms
Recv: Responder states: HTTP(0) HTTP(0)
Recv: HTTP sessions: 0 of 2
Recv: - WiFi -
Recv: Network state is starting2
Recv: WiFi module is disabled
Recv: Failed messages: pending 0, notready 0, noresp 0
Recv: Socket states: 0 ... (3 KB left)

Output from M122 P200:
Send: N14 M122 P200*85
Recv: RepRapFirmware for LPC176x based Boards (mkssgenl_2.0) version 3.2.2_2 running on LPC176x at 120Mhz
Recv: 
Recv: == Configurable Board.txt Settings ==
Recv: board = mkssgenl_2.0   Signature 0xcfc799b1
Recv: 
Recv: leds.diagnostic = 1.18
Recv: stepper.enablePins = { 2.1 2.8 0.21 2.12 0.10 NoPin NoPin }
Recv: stepper.stepPins = { 2.2 0.19 0.22 2.13 1.9 NoPin NoPin }
Recv: stepper.directionPins = { 2.3 0.20 2.11 0.11 1.14 NoPin NoPin }
Recv: stepper.digipotFactor = 0.00
Recv: stepper.TmcUartPins = { 1.1 1.8 1.10 1.15 1.17 NoPin NoPin }
Recv: stepper.numSmartDrivers = 4
Recv: stepper.TmcDiagPins = { NoPin NoPin NoPin NoPin NoPin NoPin NoPin }
Recv: heat.tempSensePins = { 0.24 0.23 NoPin NoPin }
Recv: heat.spiTempSensorCSPins = { NoPin NoPin }
Recv: heat.spiTempSensorChannel = 0
Recv: atx.powerPin = NoPin
Recv: atx.powerPinInverted = false
Recv: atx.initialPowerOn = true
Recv: sdCard.internal.spiFrequencyHz = 25000000
Recv: sdCard.external.csPin = NoPin
Recv: sdCard.external.cardDetectPin = 0.6
Recv: sdCard.external.spiFrequencyHz = 4000000
Recv: sdCard.external.spiChannel = 255
Recv: softwareSPI.pins = { NoPin NoPin NoPin }
Recv: SPI3.pins = { NoPin NoPin NoPin }
Recv: SSP0.pins = { 0.15 0.17 0.18 0.16 }
Recv: SPI0.pins = { 0.15 0.17 0.18 0.16 }
Recv: 8266wifi.espDataReadyPin = NoPin
Recv: 8266wifi.lpcTfrReadyPin = NoPin
Recv: 8266wifi.TfrReadyPin = NoPin
Recv: 8266wifi.espResetPin = NoPin
Recv: 8266wifi.serialRxTxPins = { NoPin NoPin }
Recv: serial.aux.rxTxPins = { 0.3 0.2 }
Recv: adc.prefilter.enable = true
Recv: led.neopixelPin = NoPin
Recv: 
Recv: == Defined Pins ==
Recv: e0temp,th1 = 0.23
Recv: bedtemp,TB = 0.24
Recv: e1temp,th2 = 0.25
Recv: zstopmax,Z+ = 1.24
Recv: zstop,Z- = 1.25
Recv: ystopmax,Y+ = 1.26
Recv: ystop,Y- = 1.27
Recv: xstopmax,X+ = 1.28
Recv: xstop,X- = 1.29
Recv: bed = 2.5
Recv: e0heat,e1 = 2.7
Recv: e1heat,e2 = 2.6
Recv: fan0,P2.4 = 2.4
Recv: fan1,P1.4 = 1.4
Recv: servo0,P1.23 = 1.23
Recv: servo1,P2.0 = 2.0
Recv: led4,P1.21 = 1.21
Recv: led3,P1.20 = 1.20
Recv: led2,P1.19 = 1.19
Recv: led1,P1.18 = 1.18
Recv: P1.31 = 1.31
Recv: P1.30 = 1.30
Recv: P0.18 = 0.18
Recv: P0.16 = 0.16
Recv: P0.15 = 0.15
Recv: P0.17 = 0.17
Recv: P1.0 = 1.0
Recv: P1.22 = 1.22
Recv: P0.8 = 0.8
Recv: P0.7 = 0.7
Recv: P3.25 = 3.25
Recv: P0.28 = 0.28
Recv: P3.26 = 3.26
Recv: P0.9 = 0.9
Recv: P0.27 = 0.27
Recv: P1.16 = 1.16
Recv: P0.4 = 0.4
Recv: P0.5 = 0.5
Recv: P0.26 = 0.26
Recv: P0.2 = 0.2
Recv: P0.3 = 0.3
Recv: P4.28 = 4.28
Recv: P4.29 = 4.29
Recv: 
Recv: == Hardware Serial ==
Recv: AUX Serial: UART 0
Recv: WIFI Serial: Disabled
Recv: 
Recv: == Software PWM ==
Recv: Pin 2.5 @ 250Hz (Disabled)
Recv: Pin 2.7 @ 250Hz (Disabled)
Recv: Pin 2.4 @ 5000Hz (Disabled)
Recv: Pin 1.4 @ 500Hz (Disabled)
Recv: 
Recv: == Hardware PWM ==
Recv: Hardware PWM = 50Hz [ NoPin NoPin NoPin NoPin NoPin NoPin ]
Recv: o... (3 KB left)

board.txt:
// Board Hardware configuration file for MKS SGen L v2.0
// generated by RepRapFirmware Configuration Tool (LPC Version) v3.2.1-LPC+10 
// on Sat Apr 24 2021 22:46:50 GMT+1000 (Australian Eastern Standard Time)

//Note: Each line should be less than 120 characters.
//    : Unwanted options can be commented out or set to NoPin. Lines commented out will get default values
//    : for pins the default is NoPin.
//    : Values for Arrays need to be contained within { and }
//    : Comments can be defined with // or # (comments are not supported inside arrays)
//    : Each config entry must be all on a single line.

board = mkssgenl_2.0; 

//LED blinks to indicate Platform is spinning or other diagnostic 
//Comment out or set to NoPin if not wanted.
leds.diagnostic = 1.18; 

heat.tempSensePins = {bedtemp, e0temp}; //Max of 3 entries
//heat.spiTempSensorCSPins = { }; //Max of 2 entries

//TMC Smart Drivers
stepper.numSmartDrivers = 4;

**Comment by gloomyandy** [comment]
Please continue to use our discord server to discus this. All of the folks that are likely to be able to help monitor discord, not all of them monitor these issues. I do not have access to an MKS board or MKS stepper drivers so can't try and reproduce the issues you are having. I think that PCR may have this board, so you should try tagging him on discord.
