### ISSUE TITLE
Motor phase disconnected

### ISSUE THREAD

**Issue by mmoustache** [gloomyandy/RepRapFirmware#9]
Hello guys. I and my mate having same problem with this firmware. 
Warning: motor phase A may be disconnected reported by driver(s) 1
Warning: motor phase A may be disconnected reported by driver(s) 0

on original DuetWifi on same config there are no errors. Maybe someone has this issuaes and know how to fix?

**Comment by gloomyandy** [comment]
Sorry I have only just seen this. This message is just a warning and is quite common it is very likely that there is not an actual problem. Take a look at the Duet forums and you will see a number of reports of similar warnings along with responses providing details of possible causes.
