### ISSUE TITLE
layer count not working correctly 

### ISSUE THREAD

**Issue by exiledmachinist** [gloomyandy/RepRapFirmware#90]
just upgraded to 3.2.2_2 (2021-02-19)  notice the layer count is way off after 10 actual layers counter only shows 5

**Comment by gloomyandy** [comment]
Please use our discord server for support, you might also want to look at the Duet3D forum for problems like these (which tend to be generic and are not specific to this port).

Please see: https://teamgloomy.github.io/support.html

**Comment by exiledmachinist** [comment]
thank you sir i found the issue there was a change in something with starting gcode between cura and rrf and i also forgot to update my dwc interface. im an idiot when it comes to firmware and software
