### ISSUE TITLE
How to turn on the silent mode of TMC2225？

### ISSUE THREAD

**Issue by dream111119** [gloomyandy/RepRapFirmware#91]
Hello, I use the following configuration methods in config.g
M569 P0 S0 D3 V4000 
I found that the silent mode of the driver was not turned on. I debugged and found that it was in mode 3, but it was still not muted.

In the firmware I configured
define SUPPORT_TMC22xx		1

**Comment by dream111119** [comment]
@gloomyandy

**Comment by gloomyandy** [comment]
Please use our discord server for support questions. You can find the details in our Wiki.

V4000 will probably mean that the driver will switch to spreadcycle at a very low speed, you need to use a lower value to keep it in stealthchop mode. You can use M569 P0 to see at what speed the switchover will happen.
