### ISSUE TITLE
Question - Is the Ethernet interface supported on the MKS SBase 1.3. I have a Duet Maestro and love RRF. Would like to run it on the Sbase if possible. I also ordered your wifi kit for my SKR Pro 1.1

### ISSUE THREAD

**Issue by jaymcd** [gloomyandy/RepRapFirmware#92]

**Comment by jaysuk** [comment]
its onlt supported up until 3.1.1-14. After that, support was removed

**Comment by jaymcd** [comment]
Why?

Jay M. McDonald

________________________________

**Comment by jaysuk** [comment]
no one used it and the code base was too big to fit on the LPC

**Comment by jaymcd** [comment]
Ok thanks. I will try the older version

Jay M. McDonald
________________________________
