### ISSUE TITLE
QUESTION: Pin naming to be used in RRF

### ISSUE THREAD

**Issue by reefwarrior** [gloomyandy/RepRapFirmware#96]
Hi,

I am sorry for logging an issue; but it seems like I don't get the answer I am looking for. I am utilizing RRF on the Big Tree Tech E3 RRF - however; I don't understand the naming used vs. the physical lay out of pins.

Eg. If you have eg in config.g:

M574 X1 S1 P"xstop"

But on the pins PDF the x endstop is indicated as 'X_STOP'.

I have contacted BTT but seems they don't understand what I mean/want to do. I need to eg. reconfigure the filament runout sensor to behave as a Z-min end stop; but I don't know what name to use for this to indicate the correct pin to the firmware.

eg. in the pin pdf it is given as: 'E0-STOP'

Reference: 
https://github.com/bigtreetech/BTT-E3-RRF/blob/master/BTT%20E3%20RRF%20V1.1/Hardware/BTT%20E3%20RRF%20V1.1-PIN.pdf

PLEASE help!

Tinus :)

**Comment by jaysuk** [comment]
e0stop

please see here https://teamgloomy.github.io/skr_rrf_e3_pins.html
