### ISSUE TITLE
BTT Mini 12864 and BTT E3 RRF

### ISSUE THREAD

**Issue by reefwarrior** [gloomyandy/RepRapFirmware#97]
Hi,

I am sorry if this is not the correct place, but I need a bit of support with regards to the above. I have used the tutorial from the e3 fly pro section --- the screen cycles red and then green - but there is no text - it looks asif the background has gotten too much contrast - the reset button does work; but nothing else. I have extracted the menu structure on the sd card - if I connect a classic reprap full graphic screen, then it works perfect....

All help appreciated
Tinus

**Comment by jaysuk** [comment]
please seek support on the Discord channel https://discord.gg/uS97Qs7
Thanks,

Jay
