### ISSUE TITLE
Support for STM32F1?

### ISSUE THREAD

**Issue by bergstar** [gloomyandy/RepRapFirmware#98]
STM32F1 and STM32F4 is very similiar using same devtools in general. Would it be possible to add support for STM32F1 found in Creality 4.2.2 board? It feels quite wastefull to buy a new board - just to get firmware support.

**Comment by gloomyandy** [comment]
Although it may be possible to get RRF to run on an STM32F1 processor there are several potential issues:
* Most STM32F1 boards do not have enough RAM/Flash for the STM32 version of RRF
* The mcu is considerably slower than the STM32F4 based boards
* There are probably other low level differences between the various timers/spi/adc/dma hardware devices that RRF uses
which makes a port to the STM32F1 a lot of work. Given that future versions of RRF are likely to make greater demands on all of the above, I don't think a port makes sense.
